# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tangxiangru/code/uniquelab-2017-summer-assignment-1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tangxiangru/code/uniquelab-2017-summer-assignment-1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tangxiangru/code/uniquelab-2017-summer-assignment-1/CMakeFiles /Users/tangxiangru/code/uniquelab-2017-summer-assignment-1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tangxiangru/code/uniquelab-2017-summer-assignment-1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named set

# Build rule for target.
set: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 set
.PHONY : set

# fast build rule for target.
set/fast:
	$(MAKE) -f CMakeFiles/set.dir/build.make CMakeFiles/set.dir/build
.PHONY : set/fast

#=============================================================================
# Target rules for targets named priority_queue

# Build rule for target.
priority_queue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 priority_queue
.PHONY : priority_queue

# fast build rule for target.
priority_queue/fast:
	$(MAKE) -f CMakeFiles/priority_queue.dir/build.make CMakeFiles/priority_queue.dir/build
.PHONY : priority_queue/fast

#=============================================================================
# Target rules for targets named pq_test

# Build rule for target.
pq_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pq_test
.PHONY : pq_test

# fast build rule for target.
pq_test/fast:
	$(MAKE) -f CMakeFiles/pq_test.dir/build.make CMakeFiles/pq_test.dir/build
.PHONY : pq_test/fast

#=============================================================================
# Target rules for targets named set_test

# Build rule for target.
set_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 set_test
.PHONY : set_test

# fast build rule for target.
set_test/fast:
	$(MAKE) -f CMakeFiles/set_test.dir/build.make CMakeFiles/set_test.dir/build
.PHONY : set_test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest/googlemock/gtest/CMakeFiles/gtest.dir/build.make googletest/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

pq_test.o: pq_test.cpp.o

.PHONY : pq_test.o

# target to build an object file
pq_test.cpp.o:
	$(MAKE) -f CMakeFiles/pq_test.dir/build.make CMakeFiles/pq_test.dir/pq_test.cpp.o
.PHONY : pq_test.cpp.o

pq_test.i: pq_test.cpp.i

.PHONY : pq_test.i

# target to preprocess a source file
pq_test.cpp.i:
	$(MAKE) -f CMakeFiles/pq_test.dir/build.make CMakeFiles/pq_test.dir/pq_test.cpp.i
.PHONY : pq_test.cpp.i

pq_test.s: pq_test.cpp.s

.PHONY : pq_test.s

# target to generate assembly for a file
pq_test.cpp.s:
	$(MAKE) -f CMakeFiles/pq_test.dir/build.make CMakeFiles/pq_test.dir/pq_test.cpp.s
.PHONY : pq_test.cpp.s

priority_queue.o: priority_queue.cpp.o

.PHONY : priority_queue.o

# target to build an object file
priority_queue.cpp.o:
	$(MAKE) -f CMakeFiles/priority_queue.dir/build.make CMakeFiles/priority_queue.dir/priority_queue.cpp.o
.PHONY : priority_queue.cpp.o

priority_queue.i: priority_queue.cpp.i

.PHONY : priority_queue.i

# target to preprocess a source file
priority_queue.cpp.i:
	$(MAKE) -f CMakeFiles/priority_queue.dir/build.make CMakeFiles/priority_queue.dir/priority_queue.cpp.i
.PHONY : priority_queue.cpp.i

priority_queue.s: priority_queue.cpp.s

.PHONY : priority_queue.s

# target to generate assembly for a file
priority_queue.cpp.s:
	$(MAKE) -f CMakeFiles/priority_queue.dir/build.make CMakeFiles/priority_queue.dir/priority_queue.cpp.s
.PHONY : priority_queue.cpp.s

set.o: set.cpp.o

.PHONY : set.o

# target to build an object file
set.cpp.o:
	$(MAKE) -f CMakeFiles/set.dir/build.make CMakeFiles/set.dir/set.cpp.o
.PHONY : set.cpp.o

set.i: set.cpp.i

.PHONY : set.i

# target to preprocess a source file
set.cpp.i:
	$(MAKE) -f CMakeFiles/set.dir/build.make CMakeFiles/set.dir/set.cpp.i
.PHONY : set.cpp.i

set.s: set.cpp.s

.PHONY : set.s

# target to generate assembly for a file
set.cpp.s:
	$(MAKE) -f CMakeFiles/set.dir/build.make CMakeFiles/set.dir/set.cpp.s
.PHONY : set.cpp.s

set_test.o: set_test.cpp.o

.PHONY : set_test.o

# target to build an object file
set_test.cpp.o:
	$(MAKE) -f CMakeFiles/set_test.dir/build.make CMakeFiles/set_test.dir/set_test.cpp.o
.PHONY : set_test.cpp.o

set_test.i: set_test.cpp.i

.PHONY : set_test.i

# target to preprocess a source file
set_test.cpp.i:
	$(MAKE) -f CMakeFiles/set_test.dir/build.make CMakeFiles/set_test.dir/set_test.cpp.i
.PHONY : set_test.cpp.i

set_test.s: set_test.cpp.s

.PHONY : set_test.s

# target to generate assembly for a file
set_test.cpp.s:
	$(MAKE) -f CMakeFiles/set_test.dir/build.make CMakeFiles/set_test.dir/set_test.cpp.s
.PHONY : set_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... set"
	@echo "... priority_queue"
	@echo "... edit_cache"
	@echo "... pq_test"
	@echo "... set_test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... pq_test.o"
	@echo "... pq_test.i"
	@echo "... pq_test.s"
	@echo "... priority_queue.o"
	@echo "... priority_queue.i"
	@echo "... priority_queue.s"
	@echo "... set.o"
	@echo "... set.i"
	@echo "... set.s"
	@echo "... set_test.o"
	@echo "... set_test.i"
	@echo "... set_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

